services:
  
  php-fpm:
    build:
      context: . 
      dockerfile: .docker/PHP/Dockerfile
    volumes: 
      - ./:/var/www/html
  
  apache:
    build:
      context: . 
      dockerfile: .docker/Apache/Dockerfile
    environment:
      - VIRTUAL_HOST=www.pagina.com

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"