services:
  
  php-fpm:
    build:
      context: . 
      dockerfile: .docker/PHP/Dockerfile
    volumes: 
      - ./:/var/www/html
  
  apache:
    build:
      context: . 
      dockerfile: .docker/Apache/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - php-fpm
